### ISSUE TITLE
warning: 'static uint32_t CRC32::update(uint32_t, uint8_t)' is deprecated 

### ISSUE THREAD

**Issue by mushketer888** [bakercp/CRC32#3]
/home/user/Arduino/libraries/CRC32/src/CRC32.cpp: In static member function 'static uint32_t CRC32::update(uint32_t, const uint8_t*, size_t)':
/home/user/Arduino/libraries/CRC32/src/CRC32.cpp:111:54: warning: 'static uint32_t CRC32::update(uint32_t, uint8_t)' is deprecated (declared at /home/user/Arduino/libraries/CRC32/src/CRC32.cpp:95) [-Wdeprecated-declarations]
     while(size--) checksum = update(checksum, *data++);

**Comment by vshymanskyy** [comment]
so this means, deprecated - just use new API

**Comment by bakercp** [comment]
To clarify, the static API is now deprecated.  The class based API (as used in the example) is the way to go.
