### ISSUE TITLE
Different CRC values

### ISSUE THREAD

**Issue by mrnrone** [bakercp/CRC32#4]
Hi,

I don't know it's either an active or inactive repository but after a few test it seems this lib calculates different values for the same data on Arduino Uno and Arduino Pro Mini.

**Comment by bakercp** [comment]
Odd, do the tests pass?

**Comment by bakercp** [comment]
https://github.com/bakercp/CRC32/blob/master/tests/CRC32/CRC32.ino

**Comment by FLYINGSC0T** [comment]
Hi,

Can anyone help me.

I'm also getting different CRC values. "Hello World" gives the correct checksum but with anything else they are incorrect and not what I expect.

Here is the sample code:

[Sample Code.txt](https://github.com/bakercp/CRC32/files/2817067/Sample.Code.txt)

and the output:

[Output.txt](https://github.com/bakercp/CRC32/files/2817071/Output.txt)


Ultimately I would like to use the CRC function by passing a variable to it (see run6 in the examples for the sample code and the output).

Thanks in advance anyone.

George

**Comment by bakercp** [comment]
@FLYINGSC0T what microcontroller / Arduino version are you using?

**Comment by FLYINGSC0T** [comment]
Micro controller: TTGO T-Beam ESP32
Arduino version: 1.8.6

George

**Comment by bakercp** [comment]
@FLYINGSC0T the code you provided is testing with incorrect checksums.  For instance, the following:

```c++
  // The known CRC32 Checksum for the "3405691582" string below.
  const uint32_t KNOWN_CHECKSUM = 0xCAFEBABE;

  // Create some test data. This is an array of arbitrary bytes.
  // For this test, we'll create an array of bytes representing text.
  uint8_t byteBuffer[] = "3405691582"; // "CAFEBABE"
  size_t numBytes = sizeof(byteBuffer) - 1;
```

The _hexadecimal_ number represented by `0xCAFEBABE` is the equivalent to the _decimal_ number `3405691582` (see other examples [here](https://en.wikipedia.org/wiki/Hexspeak)). This is not the same as a CRC32 checksum.  In fact, in your code you are calculating the checksum of the byte array

```c++
  uint8_t byteBuffer[] = "3405691582"; // A "string" as a byte array.
```

Which is equivalent to: 

```c++
uint8_t byteBuffer[] = {
0x33, // ascii 3
0x34, // ascii 4
0x30, // ascii 0
0x35, // ascii 5
0x36, // ascii 6
... etc
};
```

Thus, `checksum(byteBuffer) != KNOWN_CHECKSUM`.

**Comment by bakercp** [comment]
Closing this for now.  Please reopen if you can produce an invalid checksum.

**Comment by FLYINGSC0T** [comment]
Ok Christopher I now understand. In fact it's obvious!!

I overlooked that possibility and sorry for being a little stupid!!

I'll do some more tests by passing the strings to a function (via a variable) that calculates the checksums and hopefully I will get the same checksum results. ;-))

Thanks again for your time and your quick replies.

Regards,
George
