### ISSUE TITLE
does not compile for esp8266basic

### ISSUE THREAD

**Issue by ldijkman** [bakercp/CRC32#5]
does not compile for esp8266basic

arduino ide linux arm 1.8,19 raspberry pi 400

/home/pi/Arduino/libraries/ESPxWebFlMgr-master/src

when i place a lowercase copy crc32.h of CRC32.h

then it compiles

will have a look now
ESP8266WebFlMgr Demo basic
Open Filemanager with http://192.168.178.17:8080/

Elecra
https://github.com/ldijkman/randomnerd_esp32_wifi_manager

**Comment by bakercp** [comment]
Could you clarify your question? Is there a compiler error?

**Comment by ldijkman** [comment]
> Could you clarify your question? Is there a compiler error?

Yes crc32.h not found

In the cpp source it lowercase crc32.h included
Think the file is uppercase CRC32.h

Arduino ide 1.8.19 linux 32 arm raspberry pi 400

Oh i am very sory i commented on the wong github page should be holgerlembke filemanager

**Comment by ldijkman** [comment]
Oh i am very sory i commented on the wong github page should be holgerlembke filemanager
